// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.1
// source: proto/product.proto

package productpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProductService_GetProduct_FullMethodName                = "/product.ProductService/GetProduct"
	ProductService_GetStock_FullMethodName                  = "/product.ProductService/GetStock"
	ProductService_WatchProductStock_FullMethodName         = "/product.ProductService/WatchProductStock"
	ProductService_RestoreStock_FullMethodName              = "/product.ProductService/RestoreStock"
	ProductService_ConsumeStockDeductEvent_FullMethodName   = "/product.ProductService/ConsumeStockDeductEvent"
	ProductService_ConsumeRestockDeductEvent_FullMethodName = "/product.ProductService/ConsumeRestockDeductEvent"
)

// ProductServiceClient is the client API for ProductService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductServiceClient interface {
	GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*GetProductResponse, error)
	GetStock(ctx context.Context, in *GetStockRequest, opts ...grpc.CallOption) (*GetStockResponse, error)
	WatchProductStock(ctx context.Context, in *WatchProductStockRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchProductStockResponse], error)
	RestoreStock(ctx context.Context, in *RestoreStockRequest, opts ...grpc.CallOption) (*RestoreStockResponse, error)
	ConsumeStockDeductEvent(ctx context.Context, in *ConsumeStockDeductEventRequest, opts ...grpc.CallOption) (*ConsumeStockDeductEventResponse, error)
	ConsumeRestockDeductEvent(ctx context.Context, in *ConsumeStockDeductEventRequest, opts ...grpc.CallOption) (*ConsumeStockDeductEventResponse, error)
}

type productServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductServiceClient(cc grpc.ClientConnInterface) ProductServiceClient {
	return &productServiceClient{cc}
}

func (c *productServiceClient) GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*GetProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductResponse)
	err := c.cc.Invoke(ctx, ProductService_GetProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetStock(ctx context.Context, in *GetStockRequest, opts ...grpc.CallOption) (*GetStockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStockResponse)
	err := c.cc.Invoke(ctx, ProductService_GetStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) WatchProductStock(ctx context.Context, in *WatchProductStockRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchProductStockResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProductService_ServiceDesc.Streams[0], ProductService_WatchProductStock_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchProductStockRequest, WatchProductStockResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProductService_WatchProductStockClient = grpc.ServerStreamingClient[WatchProductStockResponse]

func (c *productServiceClient) RestoreStock(ctx context.Context, in *RestoreStockRequest, opts ...grpc.CallOption) (*RestoreStockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestoreStockResponse)
	err := c.cc.Invoke(ctx, ProductService_RestoreStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) ConsumeStockDeductEvent(ctx context.Context, in *ConsumeStockDeductEventRequest, opts ...grpc.CallOption) (*ConsumeStockDeductEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsumeStockDeductEventResponse)
	err := c.cc.Invoke(ctx, ProductService_ConsumeStockDeductEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) ConsumeRestockDeductEvent(ctx context.Context, in *ConsumeStockDeductEventRequest, opts ...grpc.CallOption) (*ConsumeStockDeductEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsumeStockDeductEventResponse)
	err := c.cc.Invoke(ctx, ProductService_ConsumeRestockDeductEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductServiceServer is the server API for ProductService service.
// All implementations must embed UnimplementedProductServiceServer
// for forward compatibility.
type ProductServiceServer interface {
	GetProduct(context.Context, *GetProductRequest) (*GetProductResponse, error)
	GetStock(context.Context, *GetStockRequest) (*GetStockResponse, error)
	WatchProductStock(*WatchProductStockRequest, grpc.ServerStreamingServer[WatchProductStockResponse]) error
	RestoreStock(context.Context, *RestoreStockRequest) (*RestoreStockResponse, error)
	ConsumeStockDeductEvent(context.Context, *ConsumeStockDeductEventRequest) (*ConsumeStockDeductEventResponse, error)
	ConsumeRestockDeductEvent(context.Context, *ConsumeStockDeductEventRequest) (*ConsumeStockDeductEventResponse, error)
	mustEmbedUnimplementedProductServiceServer()
}

// UnimplementedProductServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProductServiceServer struct{}

func (UnimplementedProductServiceServer) GetProduct(context.Context, *GetProductRequest) (*GetProductResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProduct not implemented")
}
func (UnimplementedProductServiceServer) GetStock(context.Context, *GetStockRequest) (*GetStockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStock not implemented")
}
func (UnimplementedProductServiceServer) WatchProductStock(*WatchProductStockRequest, grpc.ServerStreamingServer[WatchProductStockResponse]) error {
	return status.Error(codes.Unimplemented, "method WatchProductStock not implemented")
}
func (UnimplementedProductServiceServer) RestoreStock(context.Context, *RestoreStockRequest) (*RestoreStockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RestoreStock not implemented")
}
func (UnimplementedProductServiceServer) ConsumeStockDeductEvent(context.Context, *ConsumeStockDeductEventRequest) (*ConsumeStockDeductEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConsumeStockDeductEvent not implemented")
}
func (UnimplementedProductServiceServer) ConsumeRestockDeductEvent(context.Context, *ConsumeStockDeductEventRequest) (*ConsumeStockDeductEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConsumeRestockDeductEvent not implemented")
}
func (UnimplementedProductServiceServer) mustEmbedUnimplementedProductServiceServer() {}
func (UnimplementedProductServiceServer) testEmbeddedByValue()                        {}

// UnsafeProductServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductServiceServer will
// result in compilation errors.
type UnsafeProductServiceServer interface {
	mustEmbedUnimplementedProductServiceServer()
}

func RegisterProductServiceServer(s grpc.ServiceRegistrar, srv ProductServiceServer) {
	// If the following call panics, it indicates UnimplementedProductServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProductService_ServiceDesc, srv)
}

func _ProductService_GetProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_GetProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetProduct(ctx, req.(*GetProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_GetStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetStock(ctx, req.(*GetStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_WatchProductStock_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchProductStockRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProductServiceServer).WatchProductStock(m, &grpc.GenericServerStream[WatchProductStockRequest, WatchProductStockResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProductService_WatchProductStockServer = grpc.ServerStreamingServer[WatchProductStockResponse]

func _ProductService_RestoreStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).RestoreStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_RestoreStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).RestoreStock(ctx, req.(*RestoreStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_ConsumeStockDeductEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsumeStockDeductEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).ConsumeStockDeductEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_ConsumeStockDeductEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).ConsumeStockDeductEvent(ctx, req.(*ConsumeStockDeductEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_ConsumeRestockDeductEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsumeStockDeductEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).ConsumeRestockDeductEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_ConsumeRestockDeductEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).ConsumeRestockDeductEvent(ctx, req.(*ConsumeStockDeductEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductService_ServiceDesc is the grpc.ServiceDesc for ProductService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "product.ProductService",
	HandlerType: (*ProductServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProduct",
			Handler:    _ProductService_GetProduct_Handler,
		},
		{
			MethodName: "GetStock",
			Handler:    _ProductService_GetStock_Handler,
		},
		{
			MethodName: "RestoreStock",
			Handler:    _ProductService_RestoreStock_Handler,
		},
		{
			MethodName: "ConsumeStockDeductEvent",
			Handler:    _ProductService_ConsumeStockDeductEvent_Handler,
		},
		{
			MethodName: "ConsumeRestockDeductEvent",
			Handler:    _ProductService_ConsumeRestockDeductEvent_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchProductStock",
			Handler:       _ProductService_WatchProductStock_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/product.proto",
}
