// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.1
// source: services/order/proto/order.proto

package orderpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderPaidEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	PaidAt        int64                  `protobuf:"varint,4,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderPaidEvent) Reset() {
	*x = OrderPaidEvent{}
	mi := &file_services_order_proto_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderPaidEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderPaidEvent) ProtoMessage() {}

func (x *OrderPaidEvent) ProtoReflect() protoreflect.Message {
	mi := &file_services_order_proto_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderPaidEvent.ProtoReflect.Descriptor instead.
func (*OrderPaidEvent) Descriptor() ([]byte, []int) {
	return file_services_order_proto_order_proto_rawDescGZIP(), []int{0}
}

func (x *OrderPaidEvent) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OrderPaidEvent) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OrderPaidEvent) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *OrderPaidEvent) GetPaidAt() int64 {
	if x != nil {
		return x.PaidAt
	}
	return 0
}

type OrderCanceledEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     int64                  `protobuf:"varint,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Count         int64                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	CanceledAt    int64                  `protobuf:"varint,6,opt,name=canceled_at,json=canceledAt,proto3" json:"canceled_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCanceledEvent) Reset() {
	*x = OrderCanceledEvent{}
	mi := &file_services_order_proto_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCanceledEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCanceledEvent) ProtoMessage() {}

func (x *OrderCanceledEvent) ProtoReflect() protoreflect.Message {
	mi := &file_services_order_proto_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCanceledEvent.ProtoReflect.Descriptor instead.
func (*OrderCanceledEvent) Descriptor() ([]byte, []int) {
	return file_services_order_proto_order_proto_rawDescGZIP(), []int{1}
}

func (x *OrderCanceledEvent) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OrderCanceledEvent) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OrderCanceledEvent) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *OrderCanceledEvent) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *OrderCanceledEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *OrderCanceledEvent) GetCanceledAt() int64 {
	if x != nil {
		return x.CanceledAt
	}
	return 0
}

var File_services_order_proto_order_proto protoreflect.FileDescriptor

const file_services_order_proto_order_proto_rawDesc = "" +
	"\n" +
	" services/order/proto/order.proto\x12\x05order\"u\n" +
	"\x0eOrderPaidEvent\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x17\n" +
	"\apaid_at\x18\x04 \x01(\x03R\x06paidAt\"\xb6\x01\n" +
	"\x12OrderCanceledEvent\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\x03R\tproductId\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x03R\x05count\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12\x1f\n" +
	"\vcanceled_at\x18\x06 \x01(\x03R\n" +
	"canceledAtB Z\x1eproduct-service/pkg/pb/orderpbb\x06proto3"

var (
	file_services_order_proto_order_proto_rawDescOnce sync.Once
	file_services_order_proto_order_proto_rawDescData []byte
)

func file_services_order_proto_order_proto_rawDescGZIP() []byte {
	file_services_order_proto_order_proto_rawDescOnce.Do(func() {
		file_services_order_proto_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_order_proto_order_proto_rawDesc), len(file_services_order_proto_order_proto_rawDesc)))
	})
	return file_services_order_proto_order_proto_rawDescData
}

var file_services_order_proto_order_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_services_order_proto_order_proto_goTypes = []any{
	(*OrderPaidEvent)(nil),     // 0: order.OrderPaidEvent
	(*OrderCanceledEvent)(nil), // 1: order.OrderCanceledEvent
}
var file_services_order_proto_order_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_order_proto_order_proto_init() }
func file_services_order_proto_order_proto_init() {
	if File_services_order_proto_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_order_proto_order_proto_rawDesc), len(file_services_order_proto_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_services_order_proto_order_proto_goTypes,
		DependencyIndexes: file_services_order_proto_order_proto_depIdxs,
		MessageInfos:      file_services_order_proto_order_proto_msgTypes,
	}.Build()
	File_services_order_proto_order_proto = out.File
	file_services_order_proto_order_proto_goTypes = nil
	file_services_order_proto_order_proto_depIdxs = nil
}
