syntax = "proto3";

package product;

option go_package = "product-service/pkg/pb/productpb";

service ProductService {
    rpc GetProduct(GetProductRequest) returns (GetProductResponse);
    rpc GetStock(GetStockRequest) returns (GetStockResponse);
    rpc WatchProductStock(WatchProductStockRequest) returns (stream WatchProductStockResponse);
    rpc RestoreStock(RestoreStockRequest) returns (RestoreStockResponse);
    rpc ConsumeStockDeductEvent(ConsumeStockDeductEventRequest) returns (ConsumeStockDeductEventResponse);
    rpc ConsumeRestockDeductEvent(ConsumeStockDeductEventRequest) returns (ConsumeStockDeductEventResponse);
}

message GetProductRequest {
    int64 product_id = 1;
}

message GetProductResponse {
    int64 id = 1;
    string name = 2;
    int64 price = 3;
    int64 stock = 4;
}

message GetStockRequest {
    int64 product_id = 1;
}

message GetStockResponse {
    int64 stock = 1;
}


message WatchProductStockRequest {
    int64 product_id = 1;
}

message WatchProductStockResponse {
    int64 product_id = 1;
    int64 stock = 2;
    int64 seq = 3;
}

message RestoreStockRequest {
    int64 product_id = 1;
    int64 count = 2;
    string source = 3;
}

message RestoreStockResponse {
    bool success = 1;
}

message ConsumeStockDeductEventRequest {
    string event_source = 1;
    string event_id = 2;
    int64 product_id = 3;
    int64 count = 4;
    string event_type = 5;
}

message ConsumeStockDeductEventResponse {
    bool success = 1;
}