syntax = "proto3";

package user;

option go_package = "product-service/pkg/pb/userpb";

service UserService {
    rpc Register(RegisterRequest) returns (RegisterResponse) {}
    rpc Login(LoginRequest) returns (LoginResponse) {}
    rpc GetUser(GetUserRequest) returns (GetUserResponse) {}
    rpc UpdateUser(UpdateUserRequest) returns (UpdateUserResponse) {}
    rpc ListUsers(ListUsersRequest) returns (ListUsersResponse) {}
    rpc UpdatePassword(UpdatePasswordRequest) returns (UpdatePasswordResponse) {}
}

message RegisterRequest {
    string username = 1;
    string password = 2;
}
message RegisterResponse {
    int64 id = 1;
    string username = 2;
}

message LoginRequest {
    string username = 1;
    string password = 2;
}

message LoginResponse {
    string token = 1;
}
message GetUserRequest {
    int64 id = 1;
    string username = 2;
}
message GetUserResponse {
    int64 id = 1;
    string username = 2;
    string created_at = 3;
    string updated_at = 4;
}

message UpdateUserRequest {
    int64 id = 1;
    string username = 2;
    string password = 3;
}

message UpdateUserResponse {
    bool success = 1;
}

message ListUsersRequest {
    int64 page = 1;
    int64 page_size = 2;
    string keyword = 3;
    int32 status = 4;
}
message ListUsersResponse {
    repeated GetUserResponse list = 1;
    int64 total = 2;
}

message UpdatePasswordRequest {
    string username = 1;
    string old_password = 2;
    string new_password = 3;
}
message UpdatePasswordResponse {
    bool success = 1;
}


